{% set version = "1.13.2" %}

package:
  name: azure-identity-cpp
  version: {{ version }}

source:
  url: https://github.com/Azure/azure-sdk-for-cpp/archive/refs/tags/azure-identity_{{ version }}.tar.gz
  sha256: c057adbe6d2f046561f848ef8f33c110781739653575a411de828f726d8dc051
  patches:
    # https://github.com/Azure/azure-sdk-for-cpp/issues/4784
    - 0001-remove-wil-from-exported-config.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("azure-identity-cpp", max_pin="x.x.x") }}

# https://github.com/Azure/azure-sdk-for-cpp/blob/main/sdk/identity/azure-identity/vcpkg/vcpkg.json
requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cmake
    - ninja-base
  host:
    - azure-core-cpp 1.16.1
    - openssl {{ openssl }}  # [not win]
    - wil 1.0                # [win]

test:
  requires:
    - {{ compiler('cxx') }}
    - cmake
    - ninja-base
  files:
    - CMakeLists.txt
  commands:
    # shared libs
    - test -f ${PREFIX}/lib/libazure-identity${SHLIB_EXT}   # [unix]
    - if not exist %LIBRARY_BIN%\azure-identity.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\azure-identity.lib exit 1  # [win]

    # headers
    - test -f ${PREFIX}/include/azure/identity.hpp          # [unix]
    - test -f ${PREFIX}/include/azure/identity/azure_cli_credential.hpp # [unix]
    - test -f ${PREFIX}/include/azure/identity/azure_pipelines_credential.hpp # [unix]
    - test -f ${PREFIX}/include/azure/identity/chained_token_credential.hpp # [unix]
    - test -f ${PREFIX}/include/azure/identity/client_assertion_credential.hpp # [unix]
    - test -f ${PREFIX}/include/azure/identity/client_certificate_credential.hpp # [unix]
    - test -f ${PREFIX}/include/azure/identity/client_secret_credential.hpp # [unix]
    - test -f ${PREFIX}/include/azure/identity/default_azure_credential.hpp # [unix]
    - test -f ${PREFIX}/include/azure/identity/detail/client_credential_core.hpp # [unix]
    - test -f ${PREFIX}/include/azure/identity/detail/token_cache.hpp # [unix]
    - test -f ${PREFIX}/include/azure/identity/dll_import_export.hpp # [unix]
    - test -f ${PREFIX}/include/azure/identity/environment_credential.hpp # [unix]
    - test -f ${PREFIX}/include/azure/identity/managed_identity_credential.hpp # [unix]
    - test -f ${PREFIX}/include/azure/identity/rtti.hpp # [unix]
    - test -f ${PREFIX}/include/azure/identity/workload_identity_credential.hpp # [unix]
    - if not exist %LIBRARY_INC%\azure\identity.hpp exit 1  # [win]
    - if not exist %LIBRARY_INC%\azure\identity\azure_cli_credential.hpp exit 1  # [win]
    - if not exist %LIBRARY_INC%\azure\identity\azure_pipelines_credential.hpp exit 1  # [win]
    - if not exist %LIBRARY_INC%\azure\identity\chained_token_credential.hpp exit 1  # [win]
    - if not exist %LIBRARY_INC%\azure\identity\client_assertion_credential.hpp exit 1  # [win]
    - if not exist %LIBRARY_INC%\azure\identity\client_certificate_credential.hpp exit 1  # [win]
    - if not exist %LIBRARY_INC%\azure\identity\client_secret_credential.hpp exit 1  # [win]
    - if not exist %LIBRARY_INC%\azure\identity\default_azure_credential.hpp exit 1  # [win]
    - if not exist %LIBRARY_INC%\azure\identity\detail\client_credential_core.hpp exit 1  # [win]
    - if not exist %LIBRARY_INC%\azure\identity\detail\token_cache.hpp exit 1  # [win]
    - if not exist %LIBRARY_INC%\azure\identity\dll_import_export.hpp exit 1  # [win]
    - if not exist %LIBRARY_INC%\azure\identity\environment_credential.hpp exit 1  # [win]
    - if not exist %LIBRARY_INC%\azure\identity\managed_identity_credential.hpp exit 1  # [win]
    - if not exist %LIBRARY_INC%\azure\identity\rtti.hpp exit 1  # [win]
    - if not exist %LIBRARY_INC%\azure\identity\workload_identity_credential.hpp exit 1  # [win]
    # CMake metadata
    - test -f ${PREFIX}/share/azure-identity-cpp/azure-identity-cppTargets.cmake  # [unix]
    - test -f ${PREFIX}/share/azure-identity-cpp/azure-identity-cppConfig.cmake  # [unix]
    - test -f ${PREFIX}/share/azure-identity-cpp/azure-identity-cppConfigVersion.cmake  # [unix]
    - test -f ${PREFIX}/share/azure-identity-cpp/azure-identity-cppTargets-release.cmake  # [unix]
    - if not exist %LIBRARY_PREFIX%\share\azure-identity-cpp\azure-identity-cppTargets.cmake exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\share\azure-identity-cpp\azure-identity-cppConfig.cmake exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\share\azure-identity-cpp\azure-identity-cppConfigVersion.cmake  exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\share\azure-identity-cpp\azure-identity-cppTargets-release.cmake  exit 1  # [win]

    # CMake find_package()
    - cmake $CMAKE_ARGS -G Ninja -S $RECIPE_DIR -B test-find-package    # [unix]
    - cmake %CMAKE_ARGS% -G Ninja -S %RECIPE_DIR% -B test-find-package  # [win]

about:
  home: https://github.com/Azure/azure-sdk-for-cpp/
  summary: Azure Identity client library for C++
  description: >-
    The Azure Identity library provides Azure Active Directory token authentication support across the Azure SDK. It provides a set of `TokenCredential` implementations which can be used to construct Azure SDK clients which support AAD token authentication.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE.txt
    - sdk/identity/azure-identity/NOTICE.txt
  doc_url: https://azure.github.io/azure-sdk-for-cpp/
  dev_url: https://github.com/Azure/azure-sdk-for-cpp/tree/main/sdk/identity/azure-identity/

extra:
  recipe-maintainers:
    - teo-tsirpanis
    - jdblischak
    - jjerphan
    - Shelnutt2
